### ISSUE TITLE
Increase each extractor's heartbeat for faster display in the GUI on startup

### ISSUE THREAD

**Issue by KastanDay** [clowder-framework/CodeFlare-Extractors#5]
We can add a flag to each extractor's Dockerfile. In the `CMD python3 ..filename..` line, add a cmd line arg `--heartbeat 15` to set a 15 second registration heartbeat, instead of default of 5 min. 

This will dramatically improve the user experience of iterating on an extractor design. 

Thanks to @robkooper for debugging assistance.

**Comment by phantominh** [comment]
Completed in commit [de03cd3](https://github.com/clowder-framework/CodeFlare-Extractors/commit/de03cd35ac1e16d00704ab6793ad440f3d164647)
